language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest pytest-cov codecov
  - pip install -e .
  - mkdir -p test_data/files2/Subfolder/Empty

script:
  - pytest --cov .
  - sauber --duplicates --duplicate-files --duplicate-directories --duplicate-music --duplicate-videos --duplicate-images --duplicate-documents test_data

after_success:
  - codecov